# Generated by Django 5.2.3 on 2025-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='top_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scraped_Page', models.URLField(max_length=300)),
                ('Rank', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=300)),
                ('Link', models.URLField(max_length=300)),
                ('Score', models.CharField(max_length=1000)),
                ('Posted_by', models.CharField(max_length=300)),
                ('Time_ago', models.CharField(max_length=300)),
                ('Comments', models.CharField(max_length=300)),
            ],
        ),
    ]
